//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualTrip
    {
        public int ActualTripID { get; set; }
        public int ExternalTripID { get; set; }
        public int VehicleNo { get; set; }
        public int EmployeeNo { get; set; }
        public decimal Distance { get; set; }
        public decimal FuelConsumption { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string Justification { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
