//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GasCalc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Receipts = new HashSet<Receipt>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int VehicleNo { get; set; }
        public string VIN { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public string FuelType { get; set; }
        public decimal FuelConsumptionPer100 { get; set; }
        public Nullable<decimal> FuelRemainder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
